"""Distill the full-game clone-based ISMCTS teacher into a fast policy+value net, then measure
both vs the heuristic on the FULL game.

Same design as real_distill (object+card embeddings, shared pointer scorer, masked policy) but:
- full catalog: all 271 object classes + every dungeon card title (monsters + events),
- N-player encoder (own player + aggregate of opponents),
- data generated by the full-game clone-based teacher (full_teacher / fast_search),
- net plays the full game (one seat) vs the heuristic; winrate = seat-win fraction, compared on
  the same seeds/seats as the heuristic baseline.

Searched decisions = the current TREE_KINDS (flee / replay / combat-object / sacrifice / repair);
everything else (heroes, events, choose-card, ...) -> heuristic, both in the teacher and the
student. Action vocab is structural (flee/replay/resolve/none) + use_<object class>.

Usage: python full_distill.py [iters] [games] [workers] [epochs] [p_heur]
"""
import os

for _v in ('OMP_NUM_THREADS', 'MKL_NUM_THREADS', 'OPENBLAS_NUM_THREADS', 'NUMEXPR_NUM_THREADS'):
    os.environ.setdefault(_v, '1')

import multiprocessing as mp
import pickle
import random
import sys
import time

import numpy as np

import fast_search
import real_search as rs
from full_env import build_full_match, make_full_dungeon
from monstres import DonjonDeck
from objets import objets_disponibles

# --- full catalogue (from the real content, no hardcoded lists) ----------------------
CATALOG = sorted({type(o).__name__ for o in objets_disponibles})        # 271 object classes
CAT_IDX = {n: i for i, n in enumerate(CATALOG)}
CARD_TITLES = sorted({c.titre for c in DonjonDeck().cartes})            # all dungeon card titles
CARD_IDX = {t: i for i, t in enumerate(CARD_TITLES)}
KINDS = ['SHOULD_FLEE', 'SHOULD_REPLAY', 'CHOOSE_COMBAT_OBJECT',
         'CHOOSE_OBJECT_TO_SACRIFICE', 'CHOOSE_OBJECT_TO_REPAIR']
STRUCT = ['flee_no', 'flee_yes', 'replay_no', 'replay_yes', 'resolve', 'none']
VOCAB = STRUCT + ['use_' + c for c in CATALOG]
VIDX = {a: i for i, a in enumerate(VOCAB)}
NACT = len(VOCAB)
NOBJ = len(CATALOG)
NCARD = len(CARD_TITLES)
EMB = 16
# encode layout: own4 oppagg4 power1 ctitre(NCARD) deck(NCARD) phase5 owninv(NOBJ) oppinv(NOBJ)
SC0 = 8                       # 8 scalars
PW = SC0                      # power index
CT = PW + 1                   # ctitre start
DK = CT + NCARD               # deck start
PH = DK + NCARD               # phase start
II = PH + 5                   # own inv start
JJ = II + NOBJ                # opp inv start
NFEAT = JJ + NOBJ


def _inv(j):
    held = {type(o).__name__ for o in j.objets if o.intact}
    v = np.zeros(NOBJ, dtype=np.float32)
    for n in held:
        i = CAT_IDX.get(n)
        if i is not None:
            v[i] = 1.
    return v


def encode_ctx(ctx):
    p = ctx.actor
    g = ctx.game
    opps = [j for j in g.joueurs if j is not p]
    d = g.donjon
    rem = np.zeros(NCARD, dtype=np.float32)
    for idx in d.ordre[d.index:]:
        i = CARD_IDX.get(d.cartes[idx].titre)
        if i is not None:
            rem[i] += 1.
    card = ctx.subject
    cp = getattr(card, 'puissance', 0) or 0
    ctitre = np.zeros(NCARD, dtype=np.float32)
    if card is not None:
        i = CARD_IDX.get(getattr(card, 'titre', None))
        if i is not None:
            ctitre[i] = 1.
    phase = np.array([1. if ctx.kind.name == k else 0. for k in KINDS], dtype=np.float32)
    max_opp_pv = max((o.pv_total for o in opps), default=0)
    max_opp_kills = max((len(o.pile_monstres_vaincus) for o in opps), default=0)
    n_alive = sum(1 for o in opps if o.vivant)
    own_inv = _inv(p)
    opp_inv = np.zeros(NOBJ, dtype=np.float32)
    for o in opps:
        opp_inv = np.maximum(opp_inv, _inv(o))
    scal = np.array([p.pv_total / 30., len(p.pile_monstres_vaincus) / 30.,
                     min(getattr(p, 'tour', 0), 9) / 9., getattr(p, 'medailles', 0) / 5.,
                     max_opp_pv / 30., max_opp_kills / 30., n_alive / 4., len(g.joueurs) / 4.],
                    dtype=np.float32)
    return np.concatenate([scal, [cp / 10.], ctitre, rem / 4., phase, own_inv, opp_inv]).astype(np.float32)


def key_to_vocab(ctx, key):
    t = key[0]
    if t == 'b':
        return ('flee_yes' if key[1] else 'flee_no') if ctx.kind.name == 'SHOULD_FLEE' \
            else ('replay_yes' if key[1] else 'replay_no')
    if t == 'r':
        return 'resolve'
    if t == 'n':
        return 'none'
    if t == 'o':
        return 'use_' + type(list(ctx.options)[key[1]]).__name__
    return None


def legal_pairs(ctx):
    out = []
    for k in rs.legal_keys(ctx):
        v = key_to_vocab(ctx, k)
        if v is not None and v in VIDX:
            out.append((k, v))
    return out


# --- parallel data generation via the full clone-based teacher (no torch in workers) ---
class _RecPolicy(fast_search._LivePolicy):
    """fast_search live teacher that also records (encoded obs, visit-policy, legal-mask) at each
    searched decision (encoded inline, while the live ctx is valid)."""

    def __init__(self, seat, seed, n_iters, c=1.4, p_heur=0.75):
        super().__init__(seat, seed, n_iters, c=c, p_heur=p_heur)
        self.records = []

    def decide(self, ctx):
        if ctx.actor is not self.searcher or ctx.kind.name not in rs.TREE_KINDS or not rs.legal_keys(ctx):
            return self.heur.decide(ctx)
        st1, st2 = random.getstate(), np.random.get_state()
        best, visits = fast_search.fast_ismcts_decide(self.snapshot, list(self.within), self.seat,
                                                       self.seed, self.n_iters, self.c, self.p_heur)
        random.setstate(st1)
        np.random.set_state(st2)
        if best is None:
            best = rs.action_key(ctx, self.heur.decide(ctx))
        pol = np.zeros(NACT, dtype=np.float32)
        mask = np.zeros(NACT, dtype=bool)
        for k, v in legal_pairs(ctx):
            mask[VIDX[v]] = True
        tot = sum(visits.values()) or 1
        for k, cnt in visits.items():
            v = key_to_vocab(ctx, k)
            if v in VIDX:
                pol[VIDX[v]] += cnt / tot
        self.records.append([encode_ctx(ctx), pol, mask])
        self.within.append(best)
        return rs.action_from_key(ctx, best, self.heur, lambda: self.heur.decide(ctx))


def _gen_game(seed, iters, p_heur):
    from simu import ordonnanceur
    random.seed(seed)
    np.random.seed(seed & 0x7FFFFFFF)
    joueurs, reserve = build_full_match(seed)
    seat = seed % len(joueurs)
    donjon = make_full_dungeon()
    live = _RecPolicy(seat, seed, iters, p_heur=p_heur)
    winner, js = ordonnanceur(joueurs, donjon, reserve, log=False,
                              policy=live, on_turn_start=live.on_turn_start)
    z = 1.0 if winner is js[seat] else -1.0
    return [(f, p, m, z) for f, p, m in live.records], (1 if winner is js[seat] else 0)


def _gen_worker(arg):
    lo, hi, iters, p_heur = arg
    out, w, n = [], 0, 0
    for seed in range(lo, hi):
        recs, win = _gen_game(seed, iters, p_heur)
        out += recs
        w += win
        n += 1
    return out, w, n, (lo, hi)


def gen_data(games, iters, workers, p_heur, cache_path=None):
    chunk = max(1, min(5, games // (workers * 4) or 1))
    chunks = [(lo, min(lo + chunk, games), iters, p_heur) for lo in range(0, games, chunk)]
    data, w, n, done = [], 0, 0, set()
    if cache_path and os.path.exists(cache_path):
        ck = pickle.load(open(cache_path, 'rb'))
        data, w, n, done = ck['data'], ck['w'], ck['n'], set(ck['done'])
        print(f"    resume: {n} games / {len(data)} decisions cached", flush=True)
    todo = [c for c in chunks if (c[0], c[1]) not in done]
    t0 = time.perf_counter()
    n0 = n

    def absorb(res):
        nonlocal w, n
        out, cw, cn, key = res
        data.extend(out)
        w += cw
        n += cn
        done.add(key)
        if cache_path:
            tmp = cache_path + '.tmp'
            pickle.dump({'data': data, 'w': w, 'n': n, 'done': list(done)}, open(tmp, 'wb'))
            os.replace(tmp, cache_path)
        el = time.perf_counter() - t0
        eta = el / max(1, n - n0) * (games - n)
        print(f"    ... {n}/{games} games | teacher wins {w}/{n}={w/max(1,n):.0%} | "
              f"{len(data)} decisions | {el:.0f}s | ETA {eta:.0f}s", flush=True)

    if not todo:
        print("    (all cached)", flush=True)
    elif workers <= 1:
        for c in todo:
            absorb(_gen_worker(c))
    else:
        with mp.get_context('spawn').Pool(workers) as pool:
            for res in pool.imap_unordered(_gen_worker, todo):
                absorb(res)
    return data, w, n


# --- net: object + card embeddings + shared pointer scorer (same as real_distill) ------
def make_net():
    import torch
    import torch.nn as nn

    class Net(nn.Module):
        def __init__(s):
            super().__init__()
            s.obj_emb = nn.Embedding(NOBJ, EMB)
            s.card_emb = nn.Embedding(NCARD, EMB)
            s.trunk = nn.Sequential(nn.Linear(SC0 + 1 + 5 + 4 * EMB, 128), nn.ReLU(),
                                    nn.Linear(128, 128), nn.ReLU())
            s.struct = nn.Linear(128, 6)
            s.scorer = nn.Sequential(nn.Linear(128 + EMB + EMB + 1, 64), nn.ReLU(), nn.Linear(64, 1))
            s.val = nn.Linear(128, 1)
            s.register_buffer('oids', torch.arange(NOBJ))

        def forward(s, x):
            scal = x[:, :SC0]
            power = x[:, PW:PW + 1]
            ctitre = x[:, CT:CT + NCARD]
            deck = x[:, DK:DK + NCARD]
            phase = x[:, PH:PH + 5]
            owninv = x[:, II:II + NOBJ]
            oppinv = x[:, JJ:JJ + NOBJ]
            faced = ctitre @ s.card_emb.weight
            decke = deck @ s.card_emb.weight
            oe = owninv @ s.obj_emb.weight
            pe = oppinv @ s.obj_emb.weight
            h = s.trunk(torch.cat([scal, power, phase, faced, decke, oe, pe], 1))
            struct = s.struct(h)
            B = h.shape[0]
            allobj = s.obj_emb(s.oids)
            obj_in = torch.cat([h.unsqueeze(1).expand(B, NOBJ, 128),
                                allobj.unsqueeze(0).expand(B, NOBJ, EMB),
                                faced.unsqueeze(1).expand(B, NOBJ, EMB),
                                power.unsqueeze(1).expand(B, NOBJ, 1)], 2)
            obj = s.scorer(obj_in).squeeze(-1)
            return torch.cat([struct, obj], 1), s.val(h).squeeze(-1)
    return Net()


def train(net, data, epochs, val_frac=0.1):
    import copy

    import torch
    import torch.nn.functional as F
    X = torch.from_numpy(np.stack([d[0] for d in data]))
    P = torch.from_numpy(np.stack([d[1] for d in data]))
    M = torch.from_numpy(np.stack([d[2] for d in data]))
    Z = torch.from_numpy(np.asarray([d[3] for d in data], dtype=np.float32))
    n = len(data)
    g = torch.Generator().manual_seed(0)
    perm0 = torch.randperm(n, generator=g)
    nval = max(1, int(n * val_frac))
    vi, ti = perm0[:nval], perm0[nval:]
    opt = torch.optim.Adam(net.parameters(), lr=1e-3)

    def losses(idx):
        logits, val = net(X[idx])
        logits = logits.masked_fill(~M[idx], -1e9)
        lp = -(P[idx] * F.log_softmax(logits, 1)).sum(1).mean()
        lv = F.mse_loss(val, Z[idx])
        return lp, lv

    best_val, best_state, best_ep = float('inf'), None, -1
    for ep in range(epochs):
        net.train()
        perm = ti[torch.randperm(len(ti))]
        for i in range(0, len(ti), 512):
            idx = perm[i:i + 512]
            lp, lv = losses(idx)
            opt.zero_grad()
            (lp + lv).backward()
            opt.step()
        net.eval()
        with torch.no_grad():
            vlp, vlv = losses(vi)
            v = (vlp + vlv).item()
        if v < best_val:
            best_val, best_state, best_ep = v, copy.deepcopy(net.state_dict()), ep
    if best_state is not None:
        net.load_state_dict(best_state)
    net.eval()
    print(f"    best val loss {best_val:.3f} @ epoch {best_ep}/{epochs}", flush=True)


def net_action(net, ctx, heur):
    import torch
    pairs = legal_pairs(ctx)
    if not pairs:
        return heur.decide(ctx)
    with torch.no_grad():
        logits, _ = net(torch.from_numpy(encode_ctx(ctx)).unsqueeze(0))
    logits = logits[0].numpy()
    best_k, _ = max(pairs, key=lambda kv: logits[VIDX[kv[1]]])
    return rs.action_from_key(ctx, best_k, heur, lambda: heur.decide(ctx))


def eval_net_and_baseline(net, n, seed0=800000):
    from ai_policy import DefaultDungeonPolicy
    from simu import ordonnanceur

    class NetPol:
        def __init__(s, searcher):
            s.searcher, s.heur = searcher, DefaultDungeonPolicy()

        def decide(s, ctx):
            use = ctx.actor is s.searcher and ctx.kind.name in rs.TREE_KINDS and rs.legal_keys(ctx)
            return net_action(net, ctx, s.heur) if use else s.heur.decide(ctx)

    sw = hw = 0
    for g in range(n):
        seed = seed0 + g
        random.seed(seed)
        np.random.seed(seed & 0x7FFFFFFF)
        joueurs, reserve = build_full_match(seed)
        seat = seed % len(joueurs)
        winner, js = ordonnanceur(joueurs, make_full_dungeon(), reserve, log=False, policy=NetPol(joueurs[seat]))
        sw += winner is js[seat]
        random.seed(seed)
        np.random.seed(seed & 0x7FFFFFFF)
        joueurs, reserve = build_full_match(seed)
        winner, js = ordonnanceur(joueurs, make_full_dungeon(), reserve, log=False, policy=DefaultDungeonPolicy())
        hw += winner is js[seat]
    return sw / n, hw / n


if __name__ == '__main__':
    import torch
    torch.set_num_threads(1)
    ITERS = int(sys.argv[1]) if len(sys.argv) > 1 else 300
    GAMES = int(sys.argv[2]) if len(sys.argv) > 2 else 400
    WORKERS = int(sys.argv[3]) if len(sys.argv) > 3 else 10
    EPOCHS = int(sys.argv[4]) if len(sys.argv) > 4 else 200
    P_HEUR = float(sys.argv[5]) if len(sys.argv) > 5 else 0.75
    print(f"catalog: {NOBJ} objects, {NCARD} card titles, {NACT} actions, {NFEAT} features")
    print(f"[1] gen data: {GAMES} full teacher games @ {ITERS} iters, {WORKERS} workers...", flush=True)
    cache = f'artifacts/full_gen_{ITERS}_{GAMES}.pkl'
    data, w, n = gen_data(GAMES, ITERS, WORKERS, P_HEUR, cache_path=cache)
    print(f"    {len(data)} decisions; TEACHER@{ITERS} seat-win {w}/{n}={w/n:.1%}", flush=True)

    print("[2] training...", flush=True)
    net = make_net()
    train(net, data, EPOCHS)
    torch.save(net.state_dict(), 'artifacts/full_distill.pt')

    print("[3] STUDENT vs heuristic on the full game (same seeds/seats)...", flush=True)
    sw, hw = eval_net_and_baseline(net, 400)
    print(f"  STUDENT   seat-win: {sw:.1%}")
    print(f"  HEURISTIC seat-win (same seeds): {hw:.1%}")
    print(f"  -> student edge: {sw-hw:+.1%}")
    print(f"  TEACHER@{ITERS} seat-win (gen games): {w/n:.1%}")
